version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hatsusound-postgres
    environment:
      POSTGRES_DB: hatsusound
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hatsusound-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hatsusound.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
