import { BaseEntity } from './base.entity';

export class User extends BaseEntity {
  constructor(
    id: string,
    public readonly email: string,
    public readonly username: string,
    public readonly password: string,
    public readonly firstName: string,
    public readonly lastName: string,
    public readonly isActive: boolean,
    public readonly role: UserRole,
    createdAt: Date,
    updatedAt: Date,
  ) {
    super(id, createdAt, updatedAt);
  }

  static create(
    email: string,
    username: string,
    password: string,
    firstName: string,
    lastName: string,
  ): {
    email: string;
    username: string;
    password: string;
    firstName: string;
    lastName: string;
    isActive: boolean;
    role: UserRole;
  } {
    return {
      email,
      username,
      password,
      firstName,
      lastName,
      isActive: true, // isActive
      role: UserRole.USER, // default role
    };
  }

  get fullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }

  activate(): User {
    return new User(
      this.id,
      this.email,
      this.username,
      this.password,
      this.firstName,
      this.lastName,
      true,
      this.role,
      this.createdAt,
      new Date(),
    );
  }

  deactivate(): User {
    return new User(
      this.id,
      this.email,
      this.username,
      this.password,
      this.firstName,
      this.lastName,
      false,
      this.role,
      this.createdAt,
      new Date(),
    );
  }

  changeRole(newRole: UserRole): User {
    return new User(
      this.id,
      this.email,
      this.username,
      this.password,
      this.firstName,
      this.lastName,
      this.isActive,
      newRole,
      this.createdAt,
      new Date(),
    );
  }

  private static generateId(): string {
    // Ya no generamos IDs manualmente - la BD los genera
    throw new Error('IDs should be generated by the database');
  }
}

export enum UserRole {
  USER = 'user',
  ADMIN = 'admin',
  MODERATOR = 'moderator',
}
